version: "3.8"

services:
  bot:
    image: ${DOCKER_IMAGE:-OWNER/eve-chart-bot:latest}
    container_name: eve-chart-bot
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: eve-chart-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-evechartbot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:alpine
    container_name: eve-chart-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  postgres_data:
  redis_data:
